rules:
  /:
    /src:
      /**.ts:
        - file
        - PascalCaseWithABB
      /index.ts:
        - file
      /interface.json:
        - file
      /core:
        - dir
      /decorator:
        /index.ts:
        - file
      /interface:
        /index.ts:
          - file
        /*:
          - dir
          - camelCaseWithABB
      /logger:
        - dir

# 例外，支持中间用*匹配任意字符，**匹配任意路径
exceptions:
  - /.husky
  - /.vscode
  - /lib
  - /example
  - /node_modules
  - /.commitlintrc.json
  - /.dirlintrc.yml
  - /.editorconfig
  - /.eslintignore
  - /.npmignore
  - /.eslintrc.js
  - /.git
  - /.gitignore
  - /.lintstagedrc.json
  - /LICENSE
  - /package-lock.json
  - /package.json
  - /README.md
  - /CHANGELOG.md
  - /tsconfig.json

